[package]
name = "gitlucky"
version = "0.1.0"
authors = ["Evan Almloff <evanalmloff@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.6.0", features = ["router", "fullstack"] }
axum = { version = "0.7", optional = true }
tokio = { version = "1.44.1", features = ["full"], optional = true }
octocrab = { version = "0.44.0", optional = true }
serde = "1.0.219"
reqwest = { version = "0.12.15", default-features = false, features = [
    "rustls-tls",
] }
kalosm = { version = "0.4.0", features = ["remote", "language"] }
elevenlabs-api = "0.1.1"

[features]
default = ["server"]
mobile = ["dioxus/mobile"]
server = ["dioxus/server", "dep:axum", "dep:tokio", "dep:octocrab"]
dioxus = []

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
