[package]
name = "gitlucky"
version = "0.1.0"
authors = ["Evan Almloff <evanalmloff@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = { version = "0.10", features = ["vendored"] }
dioxus = { version = "0.6.0", features = ["router"] }
axum = { version = "0.7", optional = true }
tokio = { version = "1.44.1", features = ["full"] }
octocrab = { version = "0.44.0", optional = true }
serde = "1.0.219"
reqwest = { version = "0.12.15", default-features = false, features = [
    "rustls-tls",
] }
kalosm = { git = "https://github.com/floneum/floneum", features = [
    "remote",
    "language",
] }
elevenlabs-api = "0.1.1"
http = "1.3.1"
http-range = { version = "0.1.5" }
rand = "0.9.0"

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21.1"
ndk = { version = "0.9.0" }
ndk-sys = { version = "0.6.0" }
ndk-context = { version = "0.1.1" }

[features]
default = []
mobile = ["dioxus/mobile"]
server = ["dep:axum", "dep:octocrab"]
desktop = ["dioxus/desktop"]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
